### ISSUE TITLE
Some of the results are not the same as the paper.

### ISSUE THREAD

**Issue by Hiroshiba** [PKSHATechnology-Research/tdmelodic#1]
The [arXiv paper](https://arxiv.org/pdf/2009.09679.pdf) shows the following results.

```
ラグビー日本代表の試合を見に飛田給に行く。
ra[gubiinihoNda]ihyoo no shi[ai o mi] ni to[bita]kyuu ni i[ku .
```
![image](https://user-images.githubusercontent.com/4987327/107121369-5ba82100-68d5-11eb-8357-939a87679be1.png)

However, when I ran the following code from the github example, I got the following results.

```bash
echo ラグビー日本代表の試合を見に飛田給に行く。 | \
  mecab -d `mecab-config --dicdir`/tdmelodic/
```
```
ラグビー日本代表	ラ[グビーニホンダ]イヒョー	ラグビーニホンダイヒョウ	ラグビー日本代表	名詞-固有名詞-一般			@
の	ノ	ノ	の	助詞-格助詞			
試合	シアイ	シアイ	試合	名詞-普通名詞-サ変可能			0
を	オ	ヲ	を	助詞-格助詞			
見	ミ	ミル	見る	動詞-非自立可能	上一段-マ行	連用形-一般	1
に	ニ	ニ	に	助詞-格助詞			
飛田給	ト[ビタ]キュー	トビタキュウ	飛田給	名詞-固有名詞-一般			@
に	ニ	ニ	に	助詞-格助詞			
行く	イク	イク	行く	動詞-非自立可能	五段-カ行	終止形-一般	0
。			。	補助記号-句点			
EOS
```

I used the same labeling for this result as in the paper.
```
ra[gubiinihoNda]ihyoo no shiai o mi ni to[bita]kyuu ni iku .
```

The results `shiai o mi ni` and `iku` are different.

How can I get the same results as in the paper?

Thanks.

**Comment by tachi-hi** [comment]
If a word is listed in UniDic, the accent nuclei information which is registered in UniDic will be displayed on the rightmost column.

- If the rightmost column is 
  - `@`, it means that this word is listed in tdmelodic (neologd). The specific accent pattern is already embedded in the second  column.
  - `0`, `1`, `2` ..., then they are UniDic words. The number indicates the **_accent type_**  (the location of the **_accent nuclei_**.)
  - `none`: words which do not have accent patterns such as case particles (を, に, etc.), symbols, and so on.

### accent type (accent nuclei)
If the accent type is `n` (>0), the sudden fall in pitch (`]`) occurs just after the `n`-th mora.
If `n=0`, no sudden fall occurs.

https://github.com/PKSHATechnology-Research/tdmelodic/blob/master/imgs/jpn_accent_types.png

- 1-> x]xxxx
- 2-> x[x]xxx
- 3-> x[xx]xx
- 4-> x[xxx]x
- 5-> x[xxxx]
- and so on
- 0->  x[xxxx

### How to reproduce the result
We used a simple function written in a few lines to perform the following transformation.
- `shiai, 0 -> shi[ai `
- `mi, 1 -> mi]`
- `iku, 0 -> i[ku`

**Comment by Hiroshiba** [comment]
I understand completely! Thanks a lot!!
