### ISSUE TITLE
tdmelodic-sy2aの戻り値が空になる。

### ISSUE THREAD

**Issue by ryoryo34** [PKSHATechnology-Research/tdmelodic#17]
スタートガイドにある
`echo 機械学習 | docker run tdmelodic:latest tdmelodic-s2ya`
の戻り値が空になり、期待通りの結果が表示されない。（`sy2a`も）

・Unidic-tdmelodicを辞書として活用の
`echo 横浜市中区日本大通 | mecab -d `mecab-config --dicdir`/tdmelodic`
は正常に動きました。

**Comment by tachi-hi** [comment]
コマンドを書き間違えていました。
dockerの標準入力にパイプするには`-i`をつける必要がありました。
こちらを試していただいてもよろしいでしょうか。
```
echo 機械学習 | docker run -i --rm tdmelodic:latest tdmelodic-s2ya
```

**Comment by ryoryo34** [comment]
正常に動作しました！
ありがとうございます！
