### ISSUE TITLE
It seems that tdmelodic-s2ya command doesn't use neglogd

### ISSUE THREAD

**Issue by n5-suzuki** [PKSHATechnology-Research/tdmelodic#20]
Thank for your great work!

I set up your tdmelodic following [here](https://tdmelodic.readthedocs.io/ja/latest/index.html) with unidic.
Then I could predict good result by mecab command.
```
echo ラグビー日本代表の試合を見に飛田給に行く。 | mecab -d `mecab-config --dicdir`/tdmelodic/
ラグビー日本代表        ラ[グビーニホンダ]イヒョー      ラグビーニホンダイヒョウ        ラグビー日本代
表      名詞-固有名詞-一般                      @
の      ノ      ノ      の      助詞-格助詞              
試合    シアイ  シアイ  試合    名詞-普通名詞-サ変可能                  0
を      オ      ヲ      を      助詞-格助詞              
見      ミ      ミル    見る    動詞-非自立可能 上一段-マ行     連用形-一般     1
に      ニ      ニ      に      助詞-格助詞              
飛田給  ト[ビタ]キュー  トビタキュウ    飛田給  名詞-固有名詞-一般                      @
に      ニ      ニ      に      助詞-格助詞              
行く    イク    イク    行く    動詞-非自立可能 五段-カ行       終止形-一般     0
。                      。      補助記号-句点
```

But I could not predict good result by tdmelodic-s2ya command.
```
echo ラグビー日本代表の試合を見に飛田給に行く。 | tdmelodic-s2ya
ラ]グビーニ[ッポンダ]イヒョーノシアイオミ]ニヒダ]キューニイク
```

It seems that tdmelodic-s2ya command doesn't use neglogd.
Is this a specification? I want to know the way to predict by tdmelodic-s2ya command with neologd as possible.
Best regards.

**Comment by tachi-hi** [comment]
This function relies on simple reading estimation using UniDic.
https://github.com/PKSHATechnology-Research/tdmelodic/blob/master/tdmelodic/nn/convert.py#L126
The reason is simple. The docker image does not have the neologd dictionary.

It will be possible to modify the system to use neologd, but this may require some modification.
So, for the time being the following approach will solve the problem.

```
# input text.
TEXT=ラグビー日本代表の試合を見に飛田給に

# yomi prediction using mecab-unidic-neologd.
YOMI=`echo $TEXT \
        | mecab -d \`mecab-config --dicdir\`/mecab-unidic-neologd/ \
        | sed -e "/^EOS/d" | cut -f 2 | perl -pe 's/\s+//g'`

# Alternatives:
# (a) rewriting mecab-unidic-neologd/dicrc to enable the -Oyomi option.
# (b) using mecab-ipadic-neologd dictionary and -Oyomi option.
# YOMI=`echo $TEXT | mecab -Oyomi -d \`mecab-config --dicdir\`/mecab-ipadic-neologd/`

# check the result.
echo $YOMI
# the result will be
# ラグビーニホンダイヒョーノシアイオミニトビタキューニ

# accent prediction.
echo $TEXT,$YOMI | tdmelodic-sy2a
# the result will be like
# ラ[グビーニホンダ]イヒョーノシ[アイオミ]ニトビタキュ]ーニ
```

**Comment by tachi-hi** [comment]
Some notes on this issue have been added to the manual. https://github.com/PKSHATechnology-Research/tdmelodic/pull/21
